apiVersion: v1
kind: Service
metadata:
  labels:
    app: aqua-iris
  name: aqua-iris
  namespace: aqua
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: aqua-iris
  type: ClusterIP
